/**:
  estop:
    ros__parameters:
      time_step_size: 0.02

  squat:
    ros__parameters:
      time_step_size: 0.02
      duration: 1.0

  stand:
    ros__parameters:
      time_step_size: 0.02
      duration: 1.0

  base_state_estimator:
    ros__parameters:
      time_step_size: 0.001
      activate: false

  controller:
    ros__parameters:
      time_step_size: 0.02
      gainBodyPosTangential: 500.
      gainBodyVelTangential: 30.
      gainBodyPosVertical: 500.
      gainBodyVelVertical: 30.
      gainBodyOrientation: 500.
      gainBodyAngularVel: 30.
      gainSwingFootPos: 500.
      gainSwingFootVel: 30.
      maxBodyLinearAccTarget: 50.
      maxBodyAngularAccTarget: 50.
      maxJointAngularAccTarget: 10000.
      maxEndEffectorAccTarget: 1000.
      stanceFootDamping: 0.
      policy_path: /home/yarden/ethz/rl/crl/ros2_ws/src/unitree-go1-interface/data/ppo.onnx
      default_pose:
        [0.1, 0.9, -1.8, -0.1, 0.9, -1.8, 0.1, 0.9, -1.8, -0.1, 0.9, -1.8]
      action_scale: 0.5

  comm:
    ros__parameters:
      time_step_size: 0.01
      monitorPublisherQueueSize: 10
      remoteSubscriberQueueSize: 10

  robot:
    ros__parameters:
      # FL_hip, FR_hip, RL_hip, RR_hip,
      # FL_thigh, FR_thigh, RL_thigh, RR_thigh,
      # FL_calf, FR_calf, RL_calf, RR_calf
      joint_position_max:
        [
          3.14,
          3.14,
          3.14,
          3.14,
          3.14,
          3.14,
          3.14,
          3.14,
          3.14,
          3.14,
          3.14,
          3.14,
        ]
      joint_position_min:
        [
          -3.14,
          -3.14,
          -3.14,
          -3.14,
          -3.14,
          -3.14,
          -3.14,
          -3.14,
          -3.14,
          -3.14,
          -3.14,
          -3.14,
        ]
      joint_velocity_max:
        [
          206.1,
          206.1,
          206.1,
          206.1,
          206.1,
          206.1,
          206.1,
          206.1,
          206.06,
          206.06,
          206.06,
          206.06,
        ]
      joint_torque_max:
        [
          23.7,
          23.7,
          23.7,
          23.7,
          23.7,
          23.7,
          23.7,
          23.7,
          35.55,
          35.55,
          35.55,
          35.55,
        ]
      joint_position_control_kp:
        [35.0, 35.0, 35.0, 35.0, 35.0, 35.0, 35.0, 35.0, 35.0, 35.0, 35.0, 35.0]
      joint_position_control_kd:
        [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
      joint_torque_control_kp:
        [35.0, 35.0, 35.0, 35.0, 35.0, 35.0, 35.0, 35.0, 35.0, 35.0, 35.0, 35.0]
      joint_torque_control_kd:
        [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
      linear_damping: 0.0
      angular_damping: 0.0
      ground_truth_for_state: true
