go1:
  ros__parameters:
    policy_path: null
    default_pose:
      - 0.1
      - 0.9
      - -1.8
      - -0.1
      - 0.9
      - -1.8
      - 0.1
      - 0.9
      - -1.8
      - -0.1
      - 0.9
      - -1.8
    action_scale: 0.5
